events {
    worker_connections 1024;
}

http {
    upstream backend {
        # 转发到宿主机上的 8081 和 8082
        server host.docker.internal:8081 max_fails=5 fail_timeout=10s weight=1;
        server host.docker.internal:8082 max_fails=5 fail_timeout=10s weight=1;
    }

    server {
        listen 80;

        location /api {
            default_type application/json;

            keepalive_timeout 30s;
            keepalive_requests 1000;

            proxy_http_version 1.1;
            rewrite ^/api/(.*)$ /$1 break;
            proxy_pass_request_headers on;
            proxy_pass http://backend;
            proxy_next_upstream error timeout;
#             proxy_set_header Host $host;
#             proxy_set_header X-Real-IP $remote_addr;
#             proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#             proxy_set_header X-Forwarded-Proto $scheme;
            # 确保Authorization头被传递到后端
#             proxy_set_header Authorization $http_authorization;
        }
    }
}